// SPDX-License-Identifier: MPL-2.0
#include <algorithm>
#include <cerrno>
#include <climits>
#include <cstring>
#include <fcntl.h>
#include <limits>
#include <poll.h>
#include <sys/socket.h>
#include <unistd.h>
#include "ISslConnection.h"
namespace skyline::service::ssl {
    namespace {
        template<class T> std::optional<T> Arg(const ipc::IpcRequest &r,size_t o=0){if(!r.cmdArg||o>r.cmdArgSz||r.cmdArgSz-o<sizeof(T))return std::nullopt;T v{};std::memcpy(&v,r.cmdArg+o,sizeof(v));return v;}
        std::optional<span<u8>> In(ipc::IpcRequest&r,size_t i=0){if(r.inputBuf.size()<=i||!r.inputBuf[i].data())return std::nullopt;return r.inputBuf[i];}
        std::optional<span<u8>> Out(ipc::IpcRequest&r,size_t i=0){if(r.outputBuf.size()<=i||!r.outputBuf[i].data())return std::nullopt;return r.outputBuf[i];}
        ResultValue<std::vector<u8>> Serialize(const std::vector<std::vector<u8>>&certs,bool chain){if(certs.empty())return result::NoCertificate;if(!chain)return certs.front();if(certs.size()>(std::numeric_limits<u32>::max()-sizeof(ServerCertificateChainHeader))/sizeof(ServerCertificateChainEntry))return result::InsufficientMemory;u64 total{sizeof(ServerCertificateChainHeader)+certs.size()*sizeof(ServerCertificateChainEntry)};for(const auto&c:certs){total+=c.size();if(total>std::numeric_limits<u32>::max())return result::InsufficientMemory;}std::vector<u8>out(static_cast<size_t>(total));ServerCertificateChainHeader h{ServerCertificateChainMagic,static_cast<u32>(certs.size()),0};std::memcpy(out.data(),&h,sizeof(h));size_t off{sizeof(h)+certs.size()*sizeof(ServerCertificateChainEntry)};for(size_t i{};i<certs.size();++i){ServerCertificateChainEntry e{static_cast<u32>(certs[i].size()),static_cast<u32>(off)};std::memcpy(out.data()+sizeof(h)+i*sizeof(e),&e,sizeof(e));std::memcpy(out.data()+off,certs[i].data(),certs[i].size());off+=certs[i].size();}return out;}
    }
    ISslConnection::ISslConnection(const DeviceState&s,ServiceManager&m,std::shared_ptr<SslContextState>c,std::shared_ptr<TlsSessionCache>cache):BaseService(s,m),contextState(std::move(c)),sessionCache(std::move(cache)),backend(contextState,sessionCache){}
    ISslConnection::~ISslConnection(){backend.CloseNotify();if(socket>=0)::close(socket);contextState->connectionCount.fetch_sub(1);}
    Result ISslConnection::SetSocketDescriptor(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&resp){auto fd{Arg<i32>(r)};if(!fd||*fd<0)return result::InvalidSocket;if(socket>=0)return result::AlreadyInUse;sockaddr_storage peer{};socklen_t peerSize{sizeof(peer)};int kind{};socklen_t kindSize{sizeof(kind)};if(::getsockopt(*fd,SOL_SOCKET,SO_TYPE,&kind,&kindSize)||::getpeername(*fd,reinterpret_cast<sockaddr*>(&peer),&peerSize)||kind!=SOCK_STREAM)return result::InvalidSocket;int dup{::fcntl(*fd,F_DUPFD_CLOEXEC,0)};if(dup<0)return result::InvalidSocket;if(Result rc{backend.SetSocket(dup)};rc){::close(dup);return rc;}socket=dup;resp.Push<i32>(doNotCloseSocket?-1:*fd);return{};}
    Result ISslConnection::SetHostName(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&){auto b{In(r)};if(!b||b->empty()||b->size()>MaximumHostnameLength+1)return result::InvalidOption;auto end{std::find(b->begin(),b->end(),0)};if(end==b->end()||end==b->begin())return result::InvalidOption;std::string v(reinterpret_cast<const char*>(b->data()),static_cast<size_t>(end-b->begin()));if(Result rc{backend.SetHostname(v)};rc)return rc;hostname=std::move(v);return{};}
    Result ISslConnection::SetVerifyOption(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&){auto v{Arg<u32>(r)};if(!v||(*v&~VerifyAll))return result::InvalidOption;if(contextState->interfaceVersion>=2&&!skipDefaultVerify&&!contextState->allowDisableVerifyOption&&(*v&(VerifyPeerCa|VerifyHostName))!=(VerifyPeerCa|VerifyHostName))return result::InvalidOption;if((*v&VerifyEvPolicyOid)&&(*v&(VerifyPeerCa|VerifyDate))!=(VerifyPeerCa|VerifyDate))return result::InvalidOption;if(Result rc{backend.SetVerifyOption(*v)};rc)return rc;verifyOption=*v;return{};}
    Result ISslConnection::SetIoMode(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&){if(socket<0)return result::NoSocket;auto v{Arg<u32>(r)};if(!v)return result::InvalidOption;auto mode{static_cast<IoMode>(*v)};if(Result rc{backend.SetIoMode(mode)};rc)return rc;ioMode=mode;return{};}
    Result ISslConnection::GetSocketDescriptor(type::KSession&,ipc::IpcRequest&,ipc::IpcResponse&resp){if(socket<0)return result::NoSocket;int dup{::fcntl(socket,F_DUPFD_CLOEXEC,0)};if(dup<0)return result::InvalidSocket;resp.Push<i32>(dup);return{};}
    Result ISslConnection::GetHostName(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&resp){auto out{Out(r)};if(!out||out->size()<hostname.size()+1)return result::CertificateBufferTooSmall;std::memcpy(out->data(),hostname.c_str(),hostname.size()+1);resp.Push<u32>(static_cast<u32>(hostname.size()));return{};}
    Result ISslConnection::GetVerifyOption(type::KSession&,ipc::IpcRequest&,ipc::IpcResponse&resp){resp.Push<u32>(verifyOption);return{};} Result ISslConnection::GetIoMode(type::KSession&,ipc::IpcRequest&,ipc::IpcResponse&resp){resp.Push<u32>(static_cast<u32>(ioMode));return{};}
    Result ISslConnection::DoHandshakeImpl(ipc::IpcRequest&r,ipc::IpcResponse&resp,bool withCert){auto out{withCert?Out(r):std::optional<span<u8>>{}};if(withCert&&!out)return result::InvalidCertificateBufferSize;Result rc{backend.Handshake(enableAlpn)};verifyErrors=backend.VerificationErrors();if(rc)return rc;if(!withCert)return{};if(!(verifyOption&VerifyPeerCa)){resp.Push<u32>(0);resp.Push<u32>(0);return{};}auto chain{backend.PeerCertificateChain()};auto data{Serialize(chain,getServerCertChain)};if(!data)return data.result;if(out->size()<data->size())return result::CertificateBufferTooSmall;std::memcpy(out->data(),data->data(),data->size());resp.Push<u32>(static_cast<u32>(data->size()));resp.Push<u32>(getServerCertChain?static_cast<u32>(chain.size()):1);return{};}
    Result ISslConnection::DoHandshake(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&resp){return DoHandshakeImpl(r,resp,false);} Result ISslConnection::DoHandshakeGetServerCert(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&resp){return DoHandshakeImpl(r,resp,true);}
    Result ISslConnection::Read(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&resp){if(socket<0)return result::NoSocket;auto out{Out(r)};if(!out||out->empty())return result::InvalidCertificateBufferSize;size_t count{};while(count<out->size()&&!peekBuffer.empty()){(*out)[count++]=peekBuffer.front();peekBuffer.pop_front();}if(!count){auto read{backend.Read(*out)};if(!read)return read.result;count=*read;}resp.Push<u32>(static_cast<u32>(count));return{};}
    Result ISslConnection::Write(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&resp){if(socket<0)return result::NoSocket;auto in{In(r)};if(!in||in->empty())return result::InvalidCertificateBufferSize;auto written{backend.Write({in->data(),in->size()})};if(!written)return written.result;resp.Push<u32>(static_cast<u32>(*written));return{};}
    Result ISslConnection::Pending(type::KSession&,ipc::IpcRequest&,ipc::IpcResponse&resp){if(socket<0)return result::NoSocket;u64 count{peekBuffer.size()+backend.Pending()};resp.Push<i32>(static_cast<i32>(std::min<u64>(count,INT_MAX)));return{};}
    Result ISslConnection::Peek(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&resp){if(socket<0)return result::NoSocket;auto out{Out(r)};if(!out||out->empty())return result::InvalidCertificateBufferSize;if(peekBuffer.empty()){std::vector<u8>tmp(out->size());auto read{backend.Read(tmp)};if(!read)return read.result;peekBuffer.insert(peekBuffer.end(),tmp.begin(),tmp.begin()+static_cast<ptrdiff_t>(*read));}size_t count{std::min(out->size(),peekBuffer.size())};std::copy_n(peekBuffer.begin(),count,out->begin());resp.Push<u32>(static_cast<u32>(count));return{};}
    Result ISslConnection::Poll(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&resp){auto ev{Arg<u32>(r)},timeout{Arg<u32>(r,4)};if(!ev||!timeout||(*ev&~PollAll))return result::InvalidOption;if(socket<0)return result::NoSocket;u32 out{};if((*ev&PollRead)&&(!peekBuffer.empty()||backend.Pending()))out|=PollRead;if(!out){short host{};if(*ev&PollRead)host|=POLLIN;if(*ev&PollWrite)host|=POLLOUT;if(*ev&PollExcept)host|=POLLPRI;pollfd p{socket,host,0};int rc{::poll(&p,1,static_cast<int>(std::min<u32>(*timeout,INT_MAX)))};if(rc<0)return errno==EINTR?result::WouldBlock:result::IoAborted;if(p.revents&(POLLIN|POLLHUP))out|=PollRead;if(p.revents&POLLOUT)out|=PollWrite;if(p.revents&(POLLPRI|POLLERR|POLLNVAL))out|=PollExcept;}resp.Push<u32>(out);return{};}
    Result ISslConnection::GetVerifyCertError(type::KSession&,ipc::IpcRequest&,ipc::IpcResponse&){if(verifyErrors.empty())return{};Result e{verifyErrors.front()};verifyErrors.erase(verifyErrors.begin());return e;}
    Result ISslConnection::GetNeededServerCertBufferSize(type::KSession&,ipc::IpcRequest&,ipc::IpcResponse&resp){if(!backend.IsHandshaken())return result::NoConnection;auto data{Serialize(backend.PeerCertificateChain(),getServerCertChain)};if(!data)return data.result;resp.Push<u32>(static_cast<u32>(data->size()));return{};}
    Result ISslConnection::SetSessionCacheMode(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&){if(socket<0)return result::NoSocket;auto v{Arg<u32>(r)};if(!v)return result::InvalidOption;auto mode{static_cast<SessionCacheMode>(*v)};if(Result rc{backend.SetSessionCacheMode(mode)};rc)return rc;sessionCacheMode=mode;return{};} Result ISslConnection::GetSessionCacheMode(type::KSession&,ipc::IpcRequest&,ipc::IpcResponse&resp){if(socket<0)return result::NoSocket;resp.Push<u32>(static_cast<u32>(sessionCacheMode));return{};}
    Result ISslConnection::FlushSessionCache(type::KSession&,ipc::IpcRequest&,ipc::IpcResponse&){if(socket<0)return result::NoSocket;sessionCache->Flush(hostname.empty()?std::nullopt:std::optional{hostname});return{};}
    Result ISslConnection::SetRenegotiationMode(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&){if(socket<0)return result::NoSocket;auto v{Arg<u32>(r)};if(!v)return result::InvalidOption;auto mode{static_cast<RenegotiationMode>(*v)};if(Result rc{backend.SetRenegotiationMode(mode)};rc)return rc;renegotiationMode=mode;return{};} Result ISslConnection::GetRenegotiationMode(type::KSession&,ipc::IpcRequest&,ipc::IpcResponse&resp){if(socket<0)return result::NoSocket;resp.Push<u32>(static_cast<u32>(renegotiationMode));return{};}
    Result ISslConnection::SetOption(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&){auto flag{Arg<u8>(r)};auto raw{Arg<u32>(r,4)};if(!flag||!raw||*flag>1)return result::InvalidOption;auto opt{static_cast<OptionType>(*raw)};if(opt==OptionType::DoNotCloseSocket&&socket>=0)return result::AlreadyInUse;if(opt==OptionType::GetServerCertChain&&contextState->interfaceVersion<1)return result::InvalidOption;if(opt==OptionType::SkipDefaultVerify&&contextState->interfaceVersion<2)return result::InvalidOption;if(opt==OptionType::EnableAlpn&&contextState->interfaceVersion<3)return result::InvalidOption;switch(opt){case OptionType::DoNotCloseSocket:doNotCloseSocket=*flag;break;case OptionType::GetServerCertChain:getServerCertChain=*flag;break;case OptionType::SkipDefaultVerify:skipDefaultVerify=*flag;break;case OptionType::EnableAlpn:enableAlpn=*flag;break;default:return result::InvalidOption;}return{};}
    Result ISslConnection::GetOption(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&resp){auto raw{Arg<u32>(r)};if(!raw)return result::InvalidOption;auto option{static_cast<OptionType>(*raw)};if((option==OptionType::GetServerCertChain&&contextState->interfaceVersion<1)||(option==OptionType::SkipDefaultVerify&&contextState->interfaceVersion<2)||(option==OptionType::EnableAlpn&&contextState->interfaceVersion<3))return result::InvalidOption;bool v{};switch(option){case OptionType::DoNotCloseSocket:v=doNotCloseSocket;break;case OptionType::GetServerCertChain:v=getServerCertChain;break;case OptionType::SkipDefaultVerify:v=skipDefaultVerify;break;case OptionType::EnableAlpn:v=enableAlpn;break;default:return result::InvalidOption;}resp.Push<u8>(v);return{};}
    Result ISslConnection::GetVerifyCertErrors(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&resp){auto out{Out(r)};if(!out||out->size()%sizeof(Result)||out->size()<verifyErrors.size()*sizeof(Result))return result::InvalidCertificateBufferSize;if(!verifyErrors.empty())std::memcpy(out->data(),verifyErrors.data(),verifyErrors.size()*sizeof(Result));u32 count{static_cast<u32>(verifyErrors.size())};resp.Push<u32>(count);resp.Push<u32>(count);verifyErrors.clear();return{};}
    Result ISslConnection::GetCipherInfo(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&){auto v{Arg<u32>(r)};auto out{Out(r)};if(!backend.IsHandshaken())return result::NoConnection;if(!v||*v!=1||!out||out->size()!=sizeof(CipherInfo))return result::InvalidOption;CipherInfo info{};auto cipher{backend.CipherName()},protocol{backend.ProtocolVersion()};std::memcpy(info.cipher,cipher.data(),std::min(cipher.size(),sizeof(info.cipher)-1));std::memcpy(info.protocolVersion,protocol.data(),std::min(protocol.size(),sizeof(info.protocolVersion)-1));std::memcpy(out->data(),&info,sizeof(info));return{};}
    Result ISslConnection::SetNextAlpnProto(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&){if(contextState->interfaceVersion<3||socket<0)return socket<0?result::NoSocket:result::InvalidOption;auto in{In(r)};if(!in||in->size()<2)return result::InvalidOption;std::vector<std::string>protos;size_t off{};while(off<in->size()){size_t n{(*in)[off++]};if(!n||n>in->size()-off)return result::InvalidOption;protos.emplace_back(reinterpret_cast<char*>(in->data()+off),n);off+=n;}return backend.SetAlpnProtocols(std::move(protos));}
    Result ISslConnection::GetNextAlpnProto(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&resp){if(contextState->interfaceVersion<3)return result::InvalidOption;if(socket<0)return result::NoSocket;auto out{Out(r)};if(!out||out->empty())return result::InvalidCertificateBufferSize;auto p{backend.SelectedAlpn()};if(!p){std::fill(out->begin(),out->end(),0);resp.Push<u32>(static_cast<u32>(backend.IsHandshaken()&&enableAlpn?AlpnProtoState::NoOverlap:AlpnProtoState::NoSupport));resp.Push<u32>(0);return{};}if(out->size()<p->size()+1)return result::CertificateBufferTooSmall;(*out)[0]=static_cast<u8>(p->size());std::memcpy(out->data()+1,p->data(),p->size());resp.Push<u32>(static_cast<u32>(AlpnProtoState::Negotiated));resp.Push<u32>(static_cast<u32>(p->size()+1));return{};}
    Result ISslConnection::SetIoTimeout(type::KSession&,ipc::IpcRequest&r,ipc::IpcResponse&){if(contextState->version.ApiVersion()<3)return result::InvalidOption;auto v{Arg<u32>(r)};if(!v)return result::InvalidOption;backend.SetIoTimeout(*v);ioTimeoutMilliseconds=*v;return{};} Result ISslConnection::GetIoTimeout(type::KSession&,ipc::IpcRequest&,ipc::IpcResponse&resp){if(contextState->version.ApiVersion()<3)return result::InvalidOption;resp.Push<u32>(ioTimeoutMilliseconds);return{};}
    Result ISslConnection::UnsupportedModernCommand(type::KSession&,ipc::IpcRequest&,ipc::IpcResponse&){return result::InternalLogicError;}
}
