// SPDX-License-Identifier: MPL-2.0
#pragma once
#include <deque>
#include <services/serviceman.h>
#include "tls_backend.h"
namespace skyline::service::ssl {
    class ISslConnection : public BaseService {
        std::shared_ptr<SslContextState> contextState; std::shared_ptr<TlsSessionCache> sessionCache; TlsBackend backend;
        int socket{-1}; std::string hostname; u32 verifyOption{VerifyPeerCa|VerifyHostName}; IoMode ioMode{IoMode::Blocking};
        SessionCacheMode sessionCacheMode{SessionCacheMode::None}; RenegotiationMode renegotiationMode{RenegotiationMode::None};
        u32 ioTimeoutMilliseconds{DefaultIoTimeoutMilliseconds}; bool doNotCloseSocket{},getServerCertChain{},skipDefaultVerify{},enableAlpn{};
        std::deque<u8> peekBuffer; std::vector<Result> verifyErrors;
        Result DoHandshakeImpl(ipc::IpcRequest &, ipc::IpcResponse &, bool);
        Result UnsupportedModernCommand(type::KSession &, ipc::IpcRequest &, ipc::IpcResponse &);
      public:
        ISslConnection(const DeviceState &, ServiceManager &, std::shared_ptr<SslContextState>, std::shared_ptr<TlsSessionCache>); ~ISslConnection() override;
        Result SetSocketDescriptor(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result SetHostName(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result SetVerifyOption(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result SetIoMode(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &);
        Result GetSocketDescriptor(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result GetHostName(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result GetVerifyOption(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result GetIoMode(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &);
        Result DoHandshake(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result DoHandshakeGetServerCert(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result Read(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result Write(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result Pending(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result Peek(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result Poll(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &);
        Result GetVerifyCertError(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result GetNeededServerCertBufferSize(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result SetSessionCacheMode(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result GetSessionCacheMode(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result FlushSessionCache(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result SetRenegotiationMode(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result GetRenegotiationMode(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result SetOption(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result GetOption(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result GetVerifyCertErrors(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result GetCipherInfo(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result SetNextAlpnProto(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result GetNextAlpnProto(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result SetIoTimeout(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &); Result GetIoTimeout(type::KSession &,ipc::IpcRequest &,ipc::IpcResponse &);
        SERVICE_DECL(
            SFUNC(0,ISslConnection,SetSocketDescriptor),SFUNC(1,ISslConnection,SetHostName),SFUNC(2,ISslConnection,SetVerifyOption),SFUNC(3,ISslConnection,SetIoMode),SFUNC(4,ISslConnection,GetSocketDescriptor),SFUNC(5,ISslConnection,GetHostName),SFUNC(6,ISslConnection,GetVerifyOption),SFUNC(7,ISslConnection,GetIoMode),SFUNC(8,ISslConnection,DoHandshake),SFUNC(9,ISslConnection,DoHandshakeGetServerCert),SFUNC(10,ISslConnection,Read),SFUNC(11,ISslConnection,Write),SFUNC(12,ISslConnection,Pending),SFUNC(13,ISslConnection,Peek),SFUNC(14,ISslConnection,Poll),SFUNC(15,ISslConnection,GetVerifyCertError),SFUNC(16,ISslConnection,GetNeededServerCertBufferSize),SFUNC(17,ISslConnection,SetSessionCacheMode),SFUNC(18,ISslConnection,GetSessionCacheMode),SFUNC(19,ISslConnection,FlushSessionCache),SFUNC(20,ISslConnection,SetRenegotiationMode),SFUNC(21,ISslConnection,GetRenegotiationMode),SFUNC(22,ISslConnection,SetOption),SFUNC(23,ISslConnection,GetOption),SFUNC(24,ISslConnection,GetVerifyCertErrors),SFUNC(25,ISslConnection,GetCipherInfo),SFUNC(26,ISslConnection,SetNextAlpnProto),SFUNC(27,ISslConnection,GetNextAlpnProto),SFUNC(28,ISslConnection,UnsupportedModernCommand),SFUNC(29,ISslConnection,UnsupportedModernCommand),SFUNC(30,ISslConnection,UnsupportedModernCommand),SFUNC(31,ISslConnection,UnsupportedModernCommand),SFUNC(32,ISslConnection,UnsupportedModernCommand),SFUNC(33,ISslConnection,UnsupportedModernCommand),SFUNC(34,ISslConnection,SetIoTimeout),SFUNC(35,ISslConnection,GetIoTimeout),SFUNC(36,ISslConnection,UnsupportedModernCommand),SFUNC(37,ISslConnection,UnsupportedModernCommand))
    };
}
