// SPDX-License-Identifier: MPL-2.0
#include <algorithm>
#include <cerrno>
#include <climits>
#include <poll.h>
#include <sys/socket.h>
#include <mbedtls/net_sockets.h>
#include <mbedtls/x509.h>
#include "tls_backend.h"
namespace skyline::service::ssl {
    struct TlsSessionCache::Session { mbedtls_ssl_session value{}; Session(){mbedtls_ssl_session_init(&value);} ~Session(){mbedtls_ssl_session_free(&value);} };
    TlsSessionCache::TlsSessionCache() = default; TlsSessionCache::~TlsSessionCache() = default;
    bool TlsSessionCache::Load(const std::string &host, mbedtls_ssl_context &ssl) { if (host.empty()) return false; std::scoped_lock lock{mutex}; auto it{sessions.find(host)}; return it != sessions.end() && mbedtls_ssl_set_session(&ssl, &it->second->value) == 0; }
    void TlsSessionCache::Save(const std::string &host, const mbedtls_ssl_context &ssl) { if (host.empty()) return; auto session{std::make_unique<Session>()}; if (mbedtls_ssl_get_session(&ssl, &session->value)) return; std::scoped_lock lock{mutex}; sessions[host] = std::move(session); }
    u32 TlsSessionCache::Flush(const std::optional<std::string> &host) { std::scoped_lock lock{mutex}; if (!host) { u32 count{static_cast<u32>(sessions.size())}; sessions.clear(); return count; } return static_cast<u32>(sessions.erase(*host)); }
    TlsBackend::TlsBackend(std::shared_ptr<SslContextState> context, std::shared_ptr<TlsSessionCache> cache) : contextState(std::move(context)), sessionCache(std::move(cache)) {
        mbedtls_ssl_init(&ssl); mbedtls_ssl_config_init(&config); mbedtls_entropy_init(&entropy); mbedtls_ctr_drbg_init(&random);
        mbedtls_x509_crt_init(&caCertificates); mbedtls_x509_crt_init(&clientCertificate); mbedtls_pk_init(&clientPrivateKey); mbedtls_x509_crl_init(&crls);
    }
    TlsBackend::~TlsBackend() { if (handshaken) CloseNotify(); mbedtls_ssl_free(&ssl); mbedtls_ssl_config_free(&config); mbedtls_x509_crl_free(&crls); mbedtls_pk_free(&clientPrivateKey); mbedtls_x509_crt_free(&clientCertificate); mbedtls_x509_crt_free(&caCertificates); mbedtls_ctr_drbg_free(&random); mbedtls_entropy_free(&entropy); }
    int TlsBackend::SendCallback(void *ctx, const unsigned char *data, size_t size) { auto &self{*static_cast<TlsBackend *>(ctx)}; ssize_t rc{::send(self.socket, data, size, MSG_DONTWAIT | MSG_NOSIGNAL)}; if (rc >= 0) return static_cast<int>(rc); self.socketError=errno; if(errno==EAGAIN||errno==EWOULDBLOCK||errno==EINTR)return MBEDTLS_ERR_SSL_WANT_WRITE; if(errno==ECONNRESET||errno==EPIPE)return MBEDTLS_ERR_NET_CONN_RESET; return MBEDTLS_ERR_NET_SEND_FAILED; }
    int TlsBackend::ReceiveCallback(void *ctx, unsigned char *data, size_t size) { auto &self{*static_cast<TlsBackend *>(ctx)}; ssize_t rc{::recv(self.socket,data,size,MSG_DONTWAIT)}; if(rc>=0)return static_cast<int>(rc); self.socketError=errno; if(errno==EAGAIN||errno==EWOULDBLOCK||errno==EINTR)return MBEDTLS_ERR_SSL_WANT_READ; if(errno==ECONNRESET)return MBEDTLS_ERR_NET_CONN_RESET; return MBEDTLS_ERR_NET_RECV_FAILED; }
    int TlsBackend::VerifyCallback(void *ctx, mbedtls_x509_crt *, int, u32 *flags) { auto &self{*static_cast<TlsBackend *>(ctx)}; if(!(self.verifyOption&VerifyDate))*flags&=~(MBEDTLS_X509_BADCERT_EXPIRED|MBEDTLS_X509_BADCERT_FUTURE|MBEDTLS_X509_BADCRL_EXPIRED|MBEDTLS_X509_BADCRL_FUTURE); if(!(self.verifyOption&VerifyHostName))*flags&=~MBEDTLS_X509_BADCERT_CN_MISMATCH; if(!(self.verifyOption&VerifyPeerCa))*flags&=~(MBEDTLS_X509_BADCERT_NOT_TRUSTED|MBEDTLS_X509_BADCRL_NOT_TRUSTED); return 0; }
    Result TlsBackend::SetSocket(int fd){if(configured||fd<0)return configured?result::AlreadyInUse:result::InvalidSocket;socket=fd;return{};}
    Result TlsBackend::SetHostname(std::string value){if(configured)return result::AlreadyInUse;if(value.empty()||value.size()>MaximumHostnameLength||value.find('\0')!=std::string::npos)return result::InvalidOption;hostname=std::move(value);return{};}
    Result TlsBackend::SetVerifyOption(u32 value){if(configured)return result::AlreadyInUse;if(value&~VerifyAll)return result::InvalidOption;verifyOption=value;return{};}
    Result TlsBackend::SetIoMode(IoMode value){if(value!=IoMode::Blocking&&value!=IoMode::NonBlocking)return result::InvalidOption;ioMode=value;return{};}
    Result TlsBackend::SetSessionCacheMode(SessionCacheMode value){if(configured)return result::AlreadyInUse;if(value!=SessionCacheMode::None&&value!=SessionCacheMode::SessionId&&value!=SessionCacheMode::SessionTicket)return result::InvalidOption;cacheMode=value;return{};}
    Result TlsBackend::SetRenegotiationMode(RenegotiationMode value){if(configured)return result::AlreadyInUse;if(value!=RenegotiationMode::None&&value!=RenegotiationMode::Secure)return result::InvalidOption;renegotiationMode=value;return{};}
    Result TlsBackend::SetIoTimeout(u32 value){ioTimeoutMilliseconds=value;return{};}
    Result TlsBackend::SetAlpnProtocols(std::vector<std::string> values){if(configured)return result::AlreadyInUse;if(values.empty())return result::InvalidOption;alpnProtocols=std::move(values);return{};}
    Result TlsBackend::Configure(bool enableAlpn){
        if(configured)return{};
        if(socket<0)return result::NoSocket;
        if((verifyOption&VerifyHostName)&&hostname.empty())return result::InvalidCertificateDomain;
        if((verifyOption&VerifyEvPolicyOid)&&!contextState->HasPolicyOids())return result::InvalidOption;
        static constexpr char personal[]{"strato-hos-ssl"}; if(mbedtls_ctr_drbg_seed(&random,mbedtls_entropy_func,&entropy,reinterpret_cast<const unsigned char*>(personal),sizeof(personal)-1))return result::InternalLogicError;
        if(mbedtls_ssl_config_defaults(&config,MBEDTLS_SSL_IS_CLIENT,MBEDTLS_SSL_TRANSPORT_STREAM,MBEDTLS_SSL_PRESET_DEFAULT))return result::InternalLogicError;
        mbedtls_ssl_conf_rng(&config,mbedtls_ctr_drbg_random,&random); mbedtls_ssl_conf_verify(&config,VerifyCallback,this); mbedtls_ssl_conf_authmode(&config,verifyOption?MBEDTLS_SSL_VERIFY_REQUIRED:MBEDTLS_SSL_VERIFY_NONE);
        u32 protocols{contextState->version.raw&SslVersionProtocolMask}; int min{MBEDTLS_SSL_MINOR_VERSION_1},max{MBEDTLS_SSL_MINOR_VERSION_3};
        if(!(protocols&SslVersionAuto)&&protocols){if(!(protocols&SslVersionTls10))min=(protocols&SslVersionTls11)?MBEDTLS_SSL_MINOR_VERSION_2:MBEDTLS_SSL_MINOR_VERSION_3;if(!(protocols&SslVersionTls12))max=(protocols&SslVersionTls11)?MBEDTLS_SSL_MINOR_VERSION_2:MBEDTLS_SSL_MINOR_VERSION_1;}
        mbedtls_ssl_conf_min_version(&config,MBEDTLS_SSL_MAJOR_VERSION_3,min);mbedtls_ssl_conf_max_version(&config,MBEDTLS_SSL_MAJOR_VERSION_3,max);
        for(const char *path:{"/apex/com.android.conscrypt/cacerts","/system/etc/security/cacerts","/etc/ssl/certs"}){int rc{mbedtls_x509_crt_parse_path(&caCertificates,path)};if(rc>=0&&caCertificates.raw.p)break;}
        auto certs{contextState->CopyDefaultTrustedPki()};auto imported{contextState->CopyServerPki()};certs.insert(certs.end(),imported.begin(),imported.end());
        for(const auto &cert:certs){auto data{cert.data};if(cert.format==CertificateFormat::Pem&&(data.empty()||data.back()!=0))data.push_back(0);if(mbedtls_x509_crt_parse(&caCertificates,data.data(),data.size()))return result::BadCertificate;}
        for(const auto &data:contextState->CopyCrls())if(mbedtls_x509_crl_parse_der(&crls,data.data(),data.size()))return result::InvalidCrlFormat;
        mbedtls_ssl_conf_ca_chain(&config,&caCertificates,&crls);
        if(auto client{contextState->CopyClientPki()}){auto cert{client->certificate};auto key{client->privateKey};if(client->format==CertificateFormat::Pem){if(cert.empty()||cert.back()!=0)cert.push_back(0);if(key.empty()||key.back()!=0)key.push_back(0);}if(mbedtls_x509_crt_parse(&clientCertificate,cert.data(),cert.size())||mbedtls_pk_parse_key(&clientPrivateKey,key.data(),key.size(),nullptr,0)||mbedtls_ssl_conf_own_cert(&config,&clientCertificate,&clientPrivateKey))return result::BadCertificate;}
        mbedtls_ssl_conf_session_tickets(&config,cacheMode==SessionCacheMode::SessionTicket?MBEDTLS_SSL_SESSION_TICKETS_ENABLED:MBEDTLS_SSL_SESSION_TICKETS_DISABLED);mbedtls_ssl_conf_renegotiation(&config,renegotiationMode==RenegotiationMode::Secure?MBEDTLS_SSL_RENEGOTIATION_ENABLED:MBEDTLS_SSL_RENEGOTIATION_DISABLED);
        if(enableAlpn&&!alpnProtocols.empty()){for(const auto &p:alpnProtocols)alpnPointers.push_back(p.c_str());alpnPointers.push_back(nullptr);if(mbedtls_ssl_conf_alpn_protocols(&config,alpnPointers.data()))return result::InvalidOption;}
        if(mbedtls_ssl_setup(&ssl,&config))return result::InternalLogicError;
        if(!hostname.empty()&&mbedtls_ssl_set_hostname(&ssl,hostname.c_str()))return result::InvalidCertificateDomain;
        mbedtls_ssl_set_bio(&ssl,this,SendCallback,ReceiveCallback,nullptr);if(cacheMode!=SessionCacheMode::None)sessionCache->Load(hostname,ssl);configured=true;return{};
    }
    Result TlsBackend::WaitForIo(short events,std::chrono::steady_clock::time_point deadline)const{while(true){auto remaining{std::chrono::duration_cast<std::chrono::milliseconds>(deadline-std::chrono::steady_clock::now()).count()};if(remaining<=0)return result::Timeout;pollfd p{socket,events,0};int rc{::poll(&p,1,static_cast<int>(std::min<i64>(remaining,INT_MAX)))};if(rc>0)return(p.revents&(POLLERR|POLLHUP|POLLNVAL))?result::ConnectionAborted:Result{};if(rc==0)return result::Timeout;if(errno!=EINTR)return result::IoAborted;}}
    Result TlsBackend::Drive(const std::function<int()> &op,bool handshake,int &out){u32 timeout{ioMode==IoMode::NonBlocking?0:ioTimeoutMilliseconds};auto deadline{std::chrono::steady_clock::now()+std::chrono::milliseconds(timeout)};while(true){socketError=0;out=op();if(out>=0)return{};if(out!=MBEDTLS_ERR_SSL_WANT_READ&&out!=MBEDTLS_ERR_SSL_WANT_WRITE)return MapError(out,handshake);if(ioMode==IoMode::NonBlocking||!timeout)return result::WouldBlock;Result wait{WaitForIo(out==MBEDTLS_ERR_SSL_WANT_READ?POLLIN:POLLOUT,deadline)};if(wait)return wait;}}
    void TlsBackend::CollectVerificationErrors(u32 flags){verificationErrors.clear();auto add=[this](Result r){if(std::none_of(verificationErrors.begin(),verificationErrors.end(),[r](Result x){return x.raw==r.raw;}))verificationErrors.push_back(r);};if(flags&MBEDTLS_X509_BADCERT_CN_MISMATCH)add(result::InvalidCertificateDomain);if(flags&(MBEDTLS_X509_BADCERT_EXPIRED|MBEDTLS_X509_BADCERT_FUTURE))add(result::ExpiredCertificate);if(flags&MBEDTLS_X509_BADCERT_REVOKED)add(result::RevokedCertificate);if(flags&MBEDTLS_X509_BADCERT_NOT_TRUSTED)add(result::UnknownCa);if(flags&MBEDTLS_X509_BADCERT_BAD_KEY)add(result::UnsupportedCertificate);if(flags&&verificationErrors.empty())add(result::BadCertificate);}
    Result TlsBackend::MapError(int error,bool handshake){if(error==MBEDTLS_ERR_SSL_WANT_READ||error==MBEDTLS_ERR_SSL_WANT_WRITE)return result::WouldBlock;if(error==MBEDTLS_ERR_SSL_TIMEOUT)return result::Timeout;if(error==MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY)return result::AlertCloseNotify;if(error==MBEDTLS_ERR_NET_CONN_RESET)return result::ConnectionReset;if(error==MBEDTLS_ERR_X509_CERT_VERIFY_FAILED){CollectVerificationErrors(mbedtls_ssl_get_verify_result(&ssl));return verificationErrors.empty()?result::BadCertificate:verificationErrors.front();}if(socketError==EAGAIN||socketError==EWOULDBLOCK)return result::WouldBlock;switch(socketError){case ETIMEDOUT:return result::Timeout;case ECONNRESET:return result::ConnectionReset;case ECONNABORTED:return result::ConnectionAborted;case ENETDOWN:case ENETUNREACH:return result::NetworkDown;case EPIPE:case ENOTCONN:return result::SocketShutdown;case EBADF:return result::InvalidSocket;default:return handshake?result::HandshakeFailure:result::IoAborted;}}
    Result TlsBackend::Handshake(bool enableAlpn){if(handshaken)return result::AlreadyInUse;if(Result rc{Configure(enableAlpn)};rc)return rc;int out{};Result rc{Drive([this]{return mbedtls_ssl_handshake(&ssl);},true,out)};if(rc)return rc;u32 flags{mbedtls_ssl_get_verify_result(&ssl)};CollectVerificationErrors(flags);if(flags&&verifyOption)return verificationErrors.empty()?result::BadCertificate:verificationErrors.front();handshaken=true;if(cacheMode!=SessionCacheMode::None)sessionCache->Save(hostname,ssl);return{};}
    ResultValue<size_t> TlsBackend::Read(span<u8> out){if(!handshaken)return result::NoConnection;if(out.empty())return result::InvalidCertificateBufferSize;int count{};Result rc{Drive([this,out]{return mbedtls_ssl_read(&ssl,out.data(),out.size());},false,count)};if(rc.raw==result::AlertCloseNotify.raw)return size_t{};if(rc)return rc;return static_cast<size_t>(count);}
    ResultValue<size_t> TlsBackend::Write(span<const u8> in){if(!handshaken)return result::NoConnection;if(in.empty())return result::InvalidCertificateBufferSize;int count{};Result rc{Drive([this,in]{return mbedtls_ssl_write(&ssl,in.data(),in.size());},false,count)};if(rc)return rc;return static_cast<size_t>(count);}
    Result TlsBackend::CloseNotify(){if(!configured)return{};int rc{mbedtls_ssl_close_notify(&ssl)};handshaken=false;if(!rc||rc==MBEDTLS_ERR_SSL_WANT_READ||rc==MBEDTLS_ERR_SSL_WANT_WRITE)return{};return MapError(rc,false);}
    size_t TlsBackend::Pending()const{return configured?mbedtls_ssl_get_bytes_avail(&ssl):0;}
    std::vector<std::vector<u8>> TlsBackend::PeerCertificateChain()const{std::vector<std::vector<u8>> out;for(auto crt{configured?mbedtls_ssl_get_peer_cert(&ssl):nullptr};crt;crt=crt->next)out.emplace_back(crt->raw.p,crt->raw.p+crt->raw.len);return out;}
    std::vector<Result> TlsBackend::VerificationErrors()const{return verificationErrors;} std::string TlsBackend::CipherName()const{auto p{handshaken?mbedtls_ssl_get_ciphersuite(&ssl):nullptr};return p?p:"";} std::string TlsBackend::ProtocolVersion()const{auto p{handshaken?mbedtls_ssl_get_version(&ssl):nullptr};return p?p:"";} std::optional<std::string> TlsBackend::SelectedAlpn()const{auto p{handshaken?mbedtls_ssl_get_alpn_protocol(&ssl):nullptr};return p?std::optional<std::string>{p}:std::nullopt;} bool TlsBackend::IsHandshaken()const{return handshaken;}
}
